name: Compile C Project (Windows)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up MinGW-w64 (MSYS2)
      uses: msys2/setup-msys2@v2
      with:
        msystem: mingw64
        update: true
        install: >
          mingw-w64-x86_64-gcc
          make
          mingw-w64-x86_64-SDL2

    - name: Compile with Make
      shell: msys2 {0}
      run: |
        make

    - name: Locate SDL2.dll and copy to build directory
      shell: msys2 {0}
      run: |
        SDL2_DLL_PATH=$(find /mingw64/bin -name "SDL2.dll")
        echo "Found SDL2.dll at: $SDL2_DLL_PATH"
        
        mkdir release_package
        cp bf16.exe release_package/
        cp bf16_grayscale.exe release_package/
        cp "$SDL2_DLL_PATH" release_package/

    - name: Archive compiled executable and DLL
      run: |
        Compress-Archive -Path release_package -DestinationPath bf16_windows.zip
      shell: pwsh

    - name: Upload compiled package as artifact
      uses: actions/upload-artifact@v4
      with:
        name: bf16-windows-package
        path: bf16_windows.zip
