name: Compile C Project with SDL2 (Windows)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up MSVC
      uses: microsoft/setup-msbuild@v2
      with:
        msbuild-version: latest

    - name: Download SDL2 Development Libraries
      run: |
        Invoke-WebRequest -Uri "https://github.com/libsdl-org/SDL/releases/download/release-2.30.5/SDL2-devel-2.30.5-VC.zip" -OutFile "SDL2-devel.zip"
        Expand-Archive -Path "SDL2-devel.zip" -DestinationPath "."
        # Optional: Add a debug step here to verify extraction
        # Get-ChildItem -Recurse -Path "." | Select-Object FullName | Format-Table -Wrap
      shell: pwsh

    - name: Add SDL2 to PATH
      # This step is primarily for SDL2.dll at runtime, not for compilation includes/libs
      run: |
        echo "${{ github.workspace }}\SDL2-2.30.5\lib\x64" >> $env:GITHUB_PATH
        echo "${{ github.workspace }}\SDL2-2.30.5\bin\x64" >> $env:GITHUB_PATH
      shell: pwsh

    - name: Compile C Projects
      run: |
        call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64

        # Construct the full absolute path for SDL2 includes and libraries
        set "SDL2_INCLUDE_PATH=%GITHUB_WORKSPACE%\SDL2-2.30.5\include"
        set "SDL2_LIB_PATH=%GITHUB_WORKSPACE%\SDL2-2.30.5\lib\x64"

        echo "Compiling bf16.c with include path: %SDL2_INCLUDE_PATH%"
        cl.exe /EHsc /Zi bf16.c /I"%SDL2_INCLUDE_PATH%" /link /LIBPATH:"%SDL2_LIB_PATH%" SDL2.lib SDL2main.lib /out:bf16.exe

        echo "Compiling bf16_grayscale.c with include path: %SDL2_INCLUDE_PATH%"
        cl.exe /EHsc /Zi bf16_grayscale.c /I"%SDL2_INCLUDE_PATH%" /link /LIBPATH:"%SDL2_LIB_PATH%" SDL2.lib SDL2main.lib /out:bf16_grayscale.exe
      shell: cmd

    - name: Upload Color Artifact
      uses: actions/upload-artifact@v4
      with:
        name: bf16
        path: bf16.exe

    - name: Upload Grayscale Artifact
      uses: actions/upload-artifact@v4
      with:
        name: bf16_grayscale
        path: bf16_grayscale.exe
