name: Compile C Programs

on:
  push:
    branches:
      - main # Or your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install SDL2 development libraries
        run: sudo apt-get update && sudo apt-get install -y libsdl2-dev

      - name: Compile bf16.c
        run: gcc bf16.c -o bf16 -lSDL2

      - name: Compile bf16_grayscale.c
        run: gcc bf16_grayscale.c -o bf16_grayscale -lSDL2

      - name: Upload bf16 executable
        uses: actions/upload-artifact@v4
        with:
          name: bf16-executable
          path: bf16

      - name: Upload bf16_grayscale executable
        uses: actions/upload-artifact@v4
        with:
          name: bf16_grayscale-executable
          path: bf16_grayscale
